### ISSUE TITLE
Command injection in nmap web gui

### ISSUE THREAD

**Issue by ultimateshadsform** [hak5/pineapple-modules#75]
![image](https://github.com/hak5/pineapple-modules/assets/151234273/c64b16b7-f0c2-42db-919a-2988de98010d)

It's probably designed to work like this but still.

**Comment by dallaswinger** [comment]
Nmap commands in some cases can take advantage of nested bash so this might also be considered a feature by the module author.

However, as far as potential security concerns go, due to authentication being required to access this module I wouldn't categorize this as an issue. Once authenticated to the web UI there is a root web shell built in and accessible - this does not provide anything beyond that.
 
Feel free to provide additional info if I am missing some part of the picture.

**Comment by ultimateshadsform** [comment]
Yeah that's probably why
